### ISSUE TITLE
program panic when i get the url of media segments

### ISSUE THREAD

**Issue by misssonder** [grafov/m3u8#187] opened 2022-03-08 03:22 UTC
## retry this 
```golang  package main

import (
	"bytes"
	"fmt"

	"github.com/grafov/m3u8"
)

func main() {
	body := `#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PROGRAM-DATE-TIME:2022-03-01T20:15:19.786+08:00
#EXT-X-TARGETDURATION:4
#EXTINF:4.000,
test
#EXTINF:4.000,
test
#EXTINF:4.000,
test
#EXTINF:4.000,
test
#EXTINF:4.000,
test
#EXTINF:4.000,
test
#EXT-X-ENDLIST
`
	p, listType, err := m3u8.DecodeFrom(bytes.NewReader([]byte(body)), true)
	if err != nil {
		panic(err)
	}
	switch listType {
	case m3u8.MEDIA:
		mediapl := p.(*m3u8.MediaPlaylist)
		for _, segment := range mediapl.Segments {
			println(segment.URI)
		}
	case m3u8.MASTER:
		masterpl := p.(*m3u8.MasterPlaylist)
		fmt.Printf("%+v\n", masterpl)
	}
}
```
## Expected Behavior
print the url of segments
##  Actual Behavior
program panic
## Solve
https://github.com/grafov/m3u8/pull/186

**Comment by grafov** [comment] 2023-02-23 14:01
Confirmed. Thank you! I'll apply your patch to the next release.

**Comment by grafov** [comment] 2023-02-23 14:27
We have another problem after the patch:
https://github.com/grafov/m3u8/pull/186#issuecomment-1441871073
I suppose it is because we try to range over empty Segments slice. Need other solution.

**Comment by grafov** [comment] 2023-02-23 14:50
It seems we could set writer.go:325 to:

```go
	p.Segments = make([]*MediaSegment, capacity, capacity)
```
because of writer.go:372 use assign not append:
```
	p.Segments[p.tail] = seg
```

**Comment by grafov** [comment] 2023-02-23 15:23
Well, the ring buffer used inside a list of mediasegments. It was design decision made years ago :| If I were writing this today, I wouldn't repeat this decision. Hence by design the `range` loop over Segments could not possible. Maybe add a new method like GetAllSegments() could be useful for the current implementation.

**Comment by grafov** [comment] 2023-02-23 16:53
The method like:
```go
func (p *MediaPlaylist) GetAllSegments() []*MediaSegment {
	if p.count == 0 {
		return nil
	}
	buf := make([]*MediaSegment, 0, p.count)
	if p.head < p.tail {
		for i := p.head; i < p.tail; i++ {
			buf = append(buf, p.Segments[i])
		}
		return buf
	}
	for i := uint(0); i < p.tail; i++ {
		buf = append(buf, p.Segments[i])
	}
	for i := p.head; i < p.capacity; i++ {
		buf = append(buf, p.Segments[i])
	}
	return buf
}
```
Then it could be possible iterate:
```go
	for _, v := range m.GetAllSegments() {
		print(v.URI)
	}
```

**Comment by misssonder** [comment] 2023-03-02 06:25
> The method like:
> 
> ```go
> func (p *MediaPlaylist) GetAllSegments() []*MediaSegment {
> 	if p.count == 0 {
> 		return nil
> 	}
> 	buf := make([]*MediaSegment, 0, p.count)
> 	if p.head < p.tail {
> 		for i := p.head; i < p.tail; i++ {
> 			buf = append(buf, p.Segments[i])
> 		}
> 		return buf
> 	}
> 	for i := uint(0); i < p.tail; i++ {
> 		buf = append(buf, p.Segments[i])
> 	}
> 	for i := p.head; i < p.capacity; i++ {
> 		buf = append(buf, p.Segments[i])
> 	}
> 	return buf
> }
> ```
> 
> Then it could be possible iterate:
> 
> ```go
> 	for _, v := range m.GetAllSegments() {
> 		print(v.URI)
> 	}
> ```

OK, it also looks good.

**Comment by grafov** [comment] 2023-04-13 13:08
Released in https://github.com/grafov/m3u8/releases/tag/v0.12.0

**Closed by grafov** 2023-04-13 13:08 UTC
Labels: bug
